### ISSUE TITLE
[BUG] Setting an attribute with key purpose sigAuth doesn't resolve in the authentication section of document.

### ISSUE THREAD

**Issue by MichalisG** [decentralized-identity/ethr-did-resolver#95]
### Current Behavior

After setting an attribute with the key propose `sigAuth` `
```
await ethrDid.setAttribute('did/pub/Ed25519/sigAuth/hex', pubKey)
```
The key appears only in the `publicKey` section of the document but not in the `authentication` section like what I was expecting

### Expected Behavior
 Form the documentation [here](https://github.com/decentralized-identity/ethr-did-resolver#key-purposes)
specyficly this section 

> - veriKey adds a <key algorithm>VerificationKey2018 to the publicKey section of document
> - sigAuth adds a <key algorithm>SignatureAuthentication2018 to the publicKey section of document. An entry is also added to >  the authentication section of document.
> - enc adds a <key algorithm>KeyAgreementKey2019 to the publicKey section. This is used to perform a Diffie-Hellman key > exchange and derive a secret key for encrypting messages to the DID that lists such a key.

My understanding is that the entry should be added to the authentications section of the document.

Here is an example of the document I am getting 
```
{
  "@context": "https://w3id.org/did/v1",
  "id": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754",
  "publicKey": [
    {
      "id": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754#owner",
      "type": "Secp256k1VerificationKey2018",
      "owner": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754",
      "ethereumAddress": "0x4ad2b715596c1270af4069a10a13c0451c968754"
    },
    {
      "id": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754#delegate-1",
      "type": "Ed25519SignatureAuthentication2018",
      "owner": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754",
      "publicKeyHex": "31303866356238393330623164633235386162353765386630646362363932353963363162316166"
    }
  ],
  "authentication": [
    {
      "type": "Secp256k1SignatureAuthentication2018",
      "publicKey": "did:ethr:0x4ad2b715596c1270af4069a10a13c0451c968754#owner"
    }
  ]
}
```

The attribute was added with this line of code 

```
await ethrDid.setAttribute('did/pub/Ed25519/sigAuth/hex', pubKey)
```

**Comment by nikolockenvitz** [comment]
Hi @MichalisG, your invocation (`ethrDid.setAttribute(...)`) of ethr-did / the ethr-did-registry will create a `DIDAttributeChanged` event. This can only be used to add public keys and services.

What you probably want to do, is adding a delegate (not an attribute). There is [another function](https://github.com/uport-project/ethr-did-registry/blob/44712d3327e47d697a887b759b5a9357a3db69cc/contracts/EthereumDIDRegistry.sol#L78-L80) in the ethr-did-registry smart contract for that. This will create a `DIDDelegateChanged` event and the resolver will resolve this as you expect. As I am not familiar with the parameters when adding a delegate, please have a look into it [here](https://github.com/uport-project/ethr-did/blob/c9c291516ae68e1deda31a61f53c79da7ee0bafe/src/index.js#L80-L91):
```ts
async addDelegate (delegate, options = {}) {
  const delegateType = options.delegateType || Secp256k1VerificationKey2018
  const expiresIn = options.expiresIn || 86400
  const owner = await this.lookupOwner()
  return this.registry.addDelegate(
    this.address,
    delegateType,
    delegate,
    expiresIn,
    { from: owner }
  )
}
```

While this should solve your problem, I think there might be a mistake in the specification or it is at least misleading, because `sigAuth` is explicitely mentioned with DIDAttributeChanged. That should probably be corrected before closing this issue. (In case specs are correct, then implementation would not be correct).
