### ISSUE TITLE
Update Resolution Payload to latest DID Core spec

### ISSUE THREAD

**Issue by rado0x54** [decentralized-identity/ethr-did-resolver#99]
E.g. Version 12/08/2020: https://www.w3.org/TR/2020/WD-did-core-20201108/
Ideally changes are performed when DID Core spec enters the Candidate Recommendation stage.

Changes to current:
- [DID Controller](https://w3c.github.io/did-core/#did-controller)
- [assertionMethod](https://w3c.github.io/did-core/#assertion)
- [keyAgreement](https://w3c.github.io/did-core/#key-agreement)
- [Key types and formats](https://w3c.github.io/did-core/#key-types-and-formats) (publicKeyJwk, publicKeyBase58, JsonWebKey2020...)
- [EcdsaSecp256k1RecoveryMethod2020](https://github.com/decentralized-identity/EcdsaSecp256k1RecoverySignature2020)

**Comment by clehner** [comment]
Also:
- [publicKey → verificationMethod](https://github.com/w3c/did-core/pull/345)
- Consider changing `ethereumAddress` to `blockchainAccountId`. `ethereumAddress` is marked as [deprecated](https://w3c.github.io/did-spec-registries/#ethereumaddress) in [did-spec-registries](https://github.com/w3c/did-spec-registries/). But [EcdsaSecp256k1RecoverySignature2020](https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/) still uses it.

**Comment by mirceanis** [comment]
The current [`DIDAttributeChanged` scheme](https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md#public-keys) used to populate the DID document is insufficient for covering all the cases described by the more modern versions of the DID spec.

@AlexYenkalov has suggested a naming scheme that uses a set of characters to describe where a key should be placed.

```typescript
const DOCUMENT_SECTION_FLAGS = {
  v: 'verificationMethod',
  a: 'assertionMethod',
  u: 'authentication',
  k: 'keyAgreement',
  d: 'capabilityDelegation',
  i: 'capabilityInvocation',
  s: 'service'
}
```

Besides this, the `did/` prefix can also be shortened (or dropped?) to make room for more expressive future additions

So, instead of trying to match the attribute name against:
```typescript
/^did\/(pub|auth|svc)\/(\w+)(\/(\w+))?(\/(\w+))?$/
```
the resolver would look for something like this
```typescript
/^d\/([vaukdis]*)\/(\w+)(\/(\w+))?$/
```
Examples:
* if a key needs to be expressed as a `verificationMethod` and also be listed in the `authentication`, `assertionMethod`, `capabilityDelegation` and `capabilityInvocation` sections, the attribute name would start with `d/vaudi/`
* if a `keyAgreement` key is added, the attribute name would start with `d/vk/`
* if a service is added, then `d/s/`

This can be made even more efficient by recognizing that keys would always be listed in the `verificationMethod` array and referenced from the other sections, so the `/v/` flag can be dropped and considered implicit as long as the `/s/` flag is not used.

There is also the problem of the types of `verificationMethod`s that can be listed.
The names of the methods listed in the [DID spec registries](https://w3c.github.io/did-spec-registries/#verification-method-types) are quite long, so they would not fit into the 32-byte limitation of the attribute name.

To get around this problem, I propose implementing a mapping to shorter strings:
```typescript
const VERIFICATION_METHOD_TYPES: Record<string, string> = {
  jwk: 'JsonWebKey2020',
  secp256k1: 'EcdsaSecp256k1VerificationKey2019',
  secpk1Rec: 'EcdsaSecp256k1RecoveryMethod2020',
  secpk1Sch: 'SchnorrSecp256k1VerificationKey2019',
  ed25519: 'Ed25519VerificationKey2018',
  x25519: 'X25519KeyAgreementKey2019',
  blsG1: 'Bls12381G1Key2020',
  blsG2: 'Bls12381G2Key2020',
  gpg: 'GpgVerificationKey2020',
  rsa: 'RsaVerificationKey2018'
}
```

If the list of these methods is expected to remain relatively stable, an even more efficient mapping can be created:
```typescript
const VERIFICATION_METHOD_TYPES: Record<string, string> = {
  j: 'JsonWebKey2020',
  s: 'EcdsaSecp256k1VerificationKey2019',
  R: 'EcdsaSecp256k1RecoveryMethod2020',
  S: 'SchnorrSecp256k1VerificationKey2019',
  e: 'Ed25519VerificationKey2018',
  x: 'X25519KeyAgreementKey2019',
  b: 'Bls12381G1Key2020',
  B: 'Bls12381G2Key2020',
  g: 'GpgVerificationKey2020',
  r: 'RsaVerificationKey2018'
}
```

Continuing along this line of reasoning, the key encoding can be shortened to one of:
```typescript
const KEY_ENCODINGS: Record<string, string> = {
  `j`: `publicKeyJwk`,
  `58`: `publicKeyBase58`,
  `e`: `ethereumAddress`,
  `b`: `blockchainAccountId`,

  //other legacy types can also be expressed, since they are trivial to implement without dependencies:
  `16`: `publicKeyHex`,
  `64`: `publicKeyBase64`,

  //these are very inefficient in terms of storage
  `g`: `publicKeyGpg`,
  `p`: 'publicKeyPem'
}
```
There can be an implicit encoding of `base58btc`(`publicKeyBase58`) if none is specified.

Example: 
* to list an `X25519KeyAgreementKey2019` with `base58btc` encoding, one would publish an attribute with the name `d/k/x/58`
* to list an `RsaVerificationKey2018` `assertionMethod` with `publicKeyPem` encoding, one would publish an attribute with the name `d/a/r/p`
* to list an `EcdsaSecp256k1RecoveryMethod2020` `assertionMethod` and `authentication` with `ethereumAddress` encoding, one would publish an attribute with the name `d/au/R/e`

Any thoughts?

cc @awoie
